vich_uploader:
    db_driver: orm

    mappings:
       user_avatars:
           uri_prefix: /images/users/avatars
           upload_destination: '%kernel.project_dir%/public/images/users/avatars'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
